apiVersion: apps/v1

kind: ReplicaSet

metadata:
  name: green-replicaset
  labels:
    application: web-app

spec:
  template:
    metadata:
      name: green-app
      labels:
        env: dev
        application: web-app
        color: green
    spec:
      containers:
        - name: httpd
          image: varunmanik/httpd:green
  selector:
    matchLabels:
      color: green
  replicas: 5      