apiVersion: apps/v1

kind: Deployment 

metadata:
  name: blue-green-deployment
  labels:
    application: web-app

spec:
  template:
    metadata:
      name: blue-app
      labels:
        application: web-app 
        env: dev 
        color: blue
    spec:
      containers:
        - name: httpd
          image: varunmanik/httpd:green   
  selector:
    matchLabels:
      application: web-app  
  replicas: 3 